name: services
description: A collection of services to be used within the application.
publish_to: 'none'

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  faker: ^2.1.0
  firebase_auth: ^4.2.5
  flutter:
    sdk: flutter
  framework:
    path: ../framework
  models:
    path: ../models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
